name:                aoc2022
version:             0.1.0.0
github:              "tam-carre/aoc2022"
license:             BSD3
author:              "Tam CARRE"
maintainer:          "Tam CARRE"
copyright:           "2022 Tam CARRE"

description:         Please see the README on GitHub at <https://github.com/tam-carre/aoc2022#readme>

dependencies:
- base-noprelude
- relude
- hspec
- hspec-contrib
- http-client
- aeson
- http-conduit
- bytestring
- text
- vector
- containers
- lens
- lens-aeson
- mtl
- template-haskell
- time
- data-default
- base-unicode-symbols
- generic-lens
- extra
- random
- QuickCheck
- safe-exceptions
- http-types
- safe

language: GHC2021

default-extensions:
- OverloadedStrings
- OverloadedLabels
- UnicodeSyntax
- NoFieldSelectors
- LambdaCase
- DuplicateRecordFields
- ViewPatterns
- BlockArguments
- DataKinds
- TypeOperators
- TypeFamilies
- RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
  #- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc2022-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    dependencies:
    - aoc2022

tests:
  aoc2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
